### ISSUE TITLE
How to remove trailing slash?

### ISSUE THREAD

**Issue by paulocoutinhox** [Frozen-Flask/Frozen-Flask#122] opened 2021-11-12 01:02 UTC
Hi,

I made a site with this (https://util123.com/) but i need now remove the last slash.

Can anyone help me?

The main project is Kaktos (https://github.com/paulocoutinhox/kaktos).

Thanks for any help.

**Comment by paulo-coutinho** [comment] 2021-11-12 18:37
Today im using:

```
@flask_app.route("/<path:path>/")
def page(path=None):
    kaktos = system.get_kaktos(path)
    return render_template(f"pages/{path}.html", kaktos=kaktos)
```

But if i remove the trailing slash:

```
@flask_app.route("/<path:path>")
def page(path=None):
    kaktos = system.get_kaktos(path)
    return render_template(f"pages/{path}.html", kaktos=kaktos)
```

I got this error:

```
environment mode: development
root dir: /Users/paulo/Developer/workspaces/python/kaktos
build dir: /Users/paulo/Developer/workspaces/python/kaktos/build
template dir: /Users/paulo/Developer/workspaces/python/kaktos/templates
building site...
/usr/local/lib/python3.9/site-packages/flask_frozen/__init__.py:205: MimetypeMismatchWarning: Filename extension of 'gallery' (type application/octet-stream) does not match Content-Type: text/html; charset=utf-8
  return set(page.url for page in self.freeze_yield())
Traceback (most recent call last):
  File "/Users/paulo/Developer/workspaces/python/kaktos/kaktos.py", line 6, in <module>
    system.process_command()
  File "/Users/paulo/Developer/workspaces/python/kaktos/modules/system.py", line 125, in process_command
    run(command_params)
  File "/Users/paulo/Developer/workspaces/python/kaktos/modules/commands/default.py", line 9, in run
    system.build_pages()
  File "/Users/paulo/Developer/workspaces/python/kaktos/modules/system.py", line 81, in build_pages
    freezer_app.freeze()
  File "/usr/local/lib/python3.9/site-packages/flask_frozen/__init__.py", line 205, in freeze
    return set(page.url for page in self.freeze_yield())
  File "/usr/local/lib/python3.9/site-packages/flask_frozen/__init__.py", line 205, in <genexpr>
    return set(page.url for page in self.freeze_yield())
  File "/usr/local/lib/python3.9/site-packages/flask_frozen/__init__.py", line 189, in freeze_yield
    new_filename = self._build_one(url, last_modified)
  File "/usr/local/lib/python3.9/site-packages/flask_frozen/__init__.py", line 372, in _build_one
    with open(filename, 'wb') as fd:
IsADirectoryError: [Errno 21] Is a directory: '/Users/paulo/Developer/workspaces/python/kaktos/build/gallery'
```

**Comment by paulocoutinhox** [comment] 2022-05-08 06:44
???

**Comment by liZe** [comment] 2023-11-12 22:05
It’s probably a duplicate of #85.

**Closed** 2023-11-12 22:06 UTC
